# Generated by Django 4.1.5 on 2023-01-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stretchgoals',
            name='total_pledged',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
