# Generated by Django 4.1.5 on 2023-01-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_stretchgoals_total_pledged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stretchgoals',
            name='total_pledged',
        ),
    ]
